version: '3.1'
services:
  adminer:
    image: adminer
    ports:
      - "8081:8080"
  db:
    # image: mysql:5.7
    image: mysql
    volumes:
      - "./.data/db:/var/lib/mysql"
      # - "./.data/mysqldb_5.7:/var/lib/mysql"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Mdevdb101!
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: MdevWordpack101!

  wordpress:
    # depends_on:
    #   - db
    #image: wordpress:5.0.3-apache
    build: ./build
    volumes:
      - "./theme:/var/www/html/wp-content/themes/robin-honey"
      - "./plugins:/var/www/html/wp-content/plugins"
      - "./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"
    # links:
    #   - db
    ports:
      - "9009:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: Mdevdb101!

volumes:
  wp-honey:
